name: DueVault CI

on:
  push:
    branches: [ main, develop, prebeta ]
  pull_request:
    branches: [ main, develop, prebeta ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run static analysis
        run: flutter analyze

      - name: Run unit and widget tests
        run: flutter test
